version: '3'

services:
  spark:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/home/jovyan/workspace:cached

    environment:
      GRANT_SUDO: "1"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs spark on the same network as the kafka container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:kafka

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an spark port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  kafka:
    image: spotify/kafka
    restart: unless-stopped

    # Add "forwardPorts": ["2181", "9092"] to **devcontainer.json** to forward Kafka locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
