# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=jupyter/all-spark-notebook:spark-3.2.0
FROM $BASE_CONTAINER
RUN pip3 install pyspark
